# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Jul 27 13:18:24 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(517, 502)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.titleLabel = QtGui.QLabel(self.centralwidget)
        self.titleLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.titleLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.titleLabel.setText(_fromUtf8(""))
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.verticalLayout_7.addWidget(self.titleLabel)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.toolHeadLabel = QtGui.QLabel(self.groupBox_3)
        self.toolHeadLabel.setObjectName(_fromUtf8("toolHeadLabel"))
        self.horizontalLayout_7.addWidget(self.toolHeadLabel)
        self.toolHeadComboBox = QtGui.QComboBox(self.groupBox_3)
        self.toolHeadComboBox.setObjectName(_fromUtf8("toolHeadComboBox"))
        self.toolHeadComboBox.addItem(_fromUtf8(""))
        self.toolHeadComboBox.addItem(_fromUtf8(""))
        self.toolHeadComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.toolHeadComboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.tipLabel_2 = QtGui.QLabel(self.groupBox_3)
        self.tipLabel_2.setObjectName(_fromUtf8("tipLabel_2"))
        self.horizontalLayout_10.addWidget(self.tipLabel_2)
        self.matNameLineEdit = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matNameLineEdit.sizePolicy().hasHeightForWidth())
        self.matNameLineEdit.setSizePolicy(sizePolicy)
        self.matNameLineEdit.setObjectName(_fromUtf8("matNameLineEdit"))
        self.horizontalLayout_10.addWidget(self.matNameLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.tipLabel_3 = QtGui.QLabel(self.groupBox_3)
        self.tipLabel_3.setObjectName(_fromUtf8("tipLabel_3"))
        self.horizontalLayout_11.addWidget(self.tipLabel_3)
        self.matVarLineEdit = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matVarLineEdit.sizePolicy().hasHeightForWidth())
        self.matVarLineEdit.setSizePolicy(sizePolicy)
        self.matVarLineEdit.setObjectName(_fromUtf8("matVarLineEdit"))
        self.horizontalLayout_11.addWidget(self.matVarLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widthLabel = QtGui.QLabel(self.groupBox_2)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.horizontalLayout.addWidget(self.widthLabel)
        self.widthSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.widthSpinBox.setMinimum(0.01)
        self.widthSpinBox.setMaximum(100.0)
        self.widthSpinBox.setSingleStep(0.1)
        self.widthSpinBox.setProperty("value", 0.8)
        self.widthSpinBox.setObjectName(_fromUtf8("widthSpinBox"))
        self.horizontalLayout.addWidget(self.widthSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.heightLabel = QtGui.QLabel(self.groupBox_2)
        self.heightLabel.setObjectName(_fromUtf8("heightLabel"))
        self.horizontalLayout_2.addWidget(self.heightLabel)
        self.heightSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.heightSpinBox.setMaximum(100.0)
        self.heightSpinBox.setSingleStep(0.1)
        self.heightSpinBox.setProperty("value", 0.8)
        self.heightSpinBox.setObjectName(_fromUtf8("heightSpinBox"))
        self.horizontalLayout_2.addWidget(self.heightSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.speedLabel = QtGui.QLabel(self.groupBox_2)
        self.speedLabel.setObjectName(_fromUtf8("speedLabel"))
        self.horizontalLayout_3.addWidget(self.speedLabel)
        self.speedSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.speedSpinBox.setMinimum(0.01)
        self.speedSpinBox.setMaximum(120.0)
        self.speedSpinBox.setProperty("value", 30.0)
        self.speedSpinBox.setObjectName(_fromUtf8("speedSpinBox"))
        self.horizontalLayout_3.addWidget(self.speedSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.areaLabel = QtGui.QLabel(self.groupBox_2)
        self.areaLabel.setObjectName(_fromUtf8("areaLabel"))
        self.horizontalLayout_4.addWidget(self.areaLabel)
        self.areaSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.areaSpinBox.setDecimals(1)
        self.areaSpinBox.setMaximum(1.5)
        self.areaSpinBox.setSingleStep(0.1)
        self.areaSpinBox.setProperty("value", 1.0)
        self.areaSpinBox.setObjectName(_fromUtf8("areaSpinBox"))
        self.horizontalLayout_4.addWidget(self.areaSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.cvLabel = QtGui.QLabel(self.groupBox_2)
        self.cvLabel.setObjectName(_fromUtf8("cvLabel"))
        self.horizontalLayout_12.addWidget(self.cvLabel)
        self.cvSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.cvSpinBox.setDecimals(1)
        self.cvSpinBox.setMaximum(1000.0)
        self.cvSpinBox.setSingleStep(10.0)
        self.cvSpinBox.setProperty("value", 0.0)
        self.cvSpinBox.setObjectName(_fromUtf8("cvSpinBox"))
        self.horizontalLayout_12.addWidget(self.cvSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tipLabel = QtGui.QLabel(self.groupBox_2)
        self.tipLabel.setObjectName(_fromUtf8("tipLabel"))
        self.horizontalLayout_6.addWidget(self.tipLabel)
        self.tipLineEdit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tipLineEdit.sizePolicy().hasHeightForWidth())
        self.tipLineEdit.setSizePolicy(sizePolicy)
        self.tipLineEdit.setObjectName(_fromUtf8("tipLineEdit"))
        self.horizontalLayout_6.addWidget(self.tipLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.psiLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.psiLabel.sizePolicy().hasHeightForWidth())
        self.psiLabel.setSizePolicy(sizePolicy)
        self.psiLabel.setObjectName(_fromUtf8("psiLabel"))
        self.horizontalLayout_5.addWidget(self.psiLabel)
        self.psiSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.psiSpinBox.setPrefix(_fromUtf8(""))
        self.psiSpinBox.setMaximum(100.0)
        self.psiSpinBox.setSingleStep(5.0)
        self.psiSpinBox.setObjectName(_fromUtf8("psiSpinBox"))
        self.horizontalLayout_5.addWidget(self.psiSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tempLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempLabel.sizePolicy().hasHeightForWidth())
        self.tempLabel.setSizePolicy(sizePolicy)
        self.tempLabel.setObjectName(_fromUtf8("tempLabel"))
        self.horizontalLayout_9.addWidget(self.tempLabel)
        self.tempSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.tempSpinBox.setDecimals(0)
        self.tempSpinBox.setMinimum(180.0)
        self.tempSpinBox.setMaximum(310.0)
        self.tempSpinBox.setSingleStep(10.0)
        self.tempSpinBox.setObjectName(_fromUtf8("tempSpinBox"))
        self.horizontalLayout_9.addWidget(self.tempSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.horizontalLayout_13.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.commentTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentTextEdit.sizePolicy().hasHeightForWidth())
        self.commentTextEdit.setSizePolicy(sizePolicy)
        self.commentTextEdit.setObjectName(_fromUtf8("commentTextEdit"))
        self.verticalLayout.addWidget(self.commentTextEdit)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.xdflButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xdflButton.sizePolicy().hasHeightForWidth())
        self.xdflButton.setSizePolicy(sizePolicy)
        self.xdflButton.setObjectName(_fromUtf8("xdflButton"))
        self.horizontalLayout_8.addWidget(self.xdflButton)
        self.toolScriptButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolScriptButton.sizePolicy().hasHeightForWidth())
        self.toolScriptButton.setSizePolicy(sizePolicy)
        self.toolScriptButton.setMinimumSize(QtCore.QSize(0, 100))
        self.toolScriptButton.setObjectName(_fromUtf8("toolScriptButton"))
        self.horizontalLayout_8.addWidget(self.toolScriptButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Material Definition", None))
        self.toolHeadLabel.setText(_translate("MainWindow", "Tool Head", None))
        self.toolHeadComboBox.setItemText(0, _translate("MainWindow", "Valve", None))
        self.toolHeadComboBox.setItemText(1, _translate("MainWindow", "Displacement", None))
        self.toolHeadComboBox.setItemText(2, _translate("MainWindow", "Plastic", None))
        self.tipLabel_2.setText(_translate("MainWindow", "Material Name", None))
        self.matNameLineEdit.setText(_translate("MainWindow", "default", None))
        self.tipLabel_3.setText(_translate("MainWindow", "Variable name", None))
        self.matVarLineEdit.setText(_translate("MainWindow", "default", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Material Calibration", None))
        self.widthLabel.setText(_translate("MainWindow", "Path Width", None))
        self.widthSpinBox.setSuffix(_translate("MainWindow", " mm", None))
        self.heightLabel.setText(_translate("MainWindow", "Path Height", None))
        self.heightSpinBox.setSuffix(_translate("MainWindow", " mm", None))
        self.speedLabel.setText(_translate("MainWindow", "Path Speed", None))
        self.speedSpinBox.setSuffix(_translate("MainWindow", " mm/s", None))
        self.areaLabel.setText(_translate("MainWindow", "Area Constant", None))
        self.cvLabel.setText(_translate("MainWindow", "Compression Volume", None))
        self.cvSpinBox.setSuffix(_translate("MainWindow", " mm^3", None))
        self.tipLabel.setText(_translate("MainWindow", "Tip", None))
        self.tipLineEdit.setText(_translate("MainWindow", "blue Taper", None))
        self.groupBox.setTitle(_translate("MainWindow", "Tool head dependant info", None))
        self.psiLabel.setText(_translate("MainWindow", "PSI", None))
        self.psiSpinBox.setSuffix(_translate("MainWindow", " PSI", None))
        self.tempLabel.setText(_translate("MainWindow", "Temprature", None))
        self.tempSpinBox.setSuffix(_translate("MainWindow", " C", None))
        self.label_2.setText(_translate("MainWindow", "Comment", None))
        self.xdflButton.setText(_translate("MainWindow", "Generate Test XDFL", None))
        self.toolScriptButton.setText(_translate("MainWindow", "Generate Toolscript", None))

