# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Jul 27 18:18:23 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 640)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 640))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.studioButton = QtGui.QPushButton(self.centralwidget)
        self.studioButton.setGeometry(QtCore.QRect(0, 480, 400, 60))
        self.studioButton.setMinimumSize(QtCore.QSize(400, 60))
        self.studioButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.studioButton.setObjectName(_fromUtf8("studioButton"))
        self.calibrateButton = QtGui.QPushButton(self.centralwidget)
        self.calibrateButton.setGeometry(QtCore.QRect(0, 540, 400, 60))
        self.calibrateButton.setMinimumSize(QtCore.QSize(400, 60))
        self.calibrateButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.calibrateButton.setObjectName(_fromUtf8("calibrateButton"))
        self.manipulateButton = QtGui.QPushButton(self.centralwidget)
        self.manipulateButton.setGeometry(QtCore.QRect(400, 480, 201, 60))
        self.manipulateButton.setMinimumSize(QtCore.QSize(200, 60))
        self.manipulateButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.manipulateButton.setObjectName(_fromUtf8("manipulateButton"))
        self.viewButton = QtGui.QPushButton(self.centralwidget)
        self.viewButton.setGeometry(QtCore.QRect(400, 540, 201, 60))
        self.viewButton.setMinimumSize(QtCore.QSize(200, 60))
        self.viewButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.viewButton.setObjectName(_fromUtf8("viewButton"))
        self.printButton = QtGui.QPushButton(self.centralwidget)
        self.printButton.setGeometry(QtCore.QRect(600, 480, 400, 60))
        self.printButton.setMinimumSize(QtCore.QSize(400, 60))
        self.printButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.printButton.setObjectName(_fromUtf8("printButton"))
        self.quitButton = QtGui.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(600, 540, 400, 60))
        self.quitButton.setMinimumSize(QtCore.QSize(400, 60))
        self.quitButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1000, 475))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1000, 475))
        self.label.setMaximumSize(QtCore.QSize(1000, 475))
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEssential_tools = QtGui.QMenu(self.menubar)
        self.menuEssential_tools.setObjectName(_fromUtf8("menuEssential_tools"))
        self.menuOptional_Advanced_Tools = QtGui.QMenu(self.menubar)
        self.menuOptional_Advanced_Tools.setObjectName(_fromUtf8("menuOptional_Advanced_Tools"))
        self.menuHelp_Manuals_Specs = QtGui.QMenu(self.menubar)
        self.menuHelp_Manuals_Specs.setObjectName(_fromUtf8("menuHelp_Manuals_Specs"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLaunch_Seraph_Studio = QtGui.QAction(MainWindow)
        self.actionLaunch_Seraph_Studio.setObjectName(_fromUtf8("actionLaunch_Seraph_Studio"))
        self.actionLaunch_Seraph_Print = QtGui.QAction(MainWindow)
        self.actionLaunch_Seraph_Print.setObjectName(_fromUtf8("actionLaunch_Seraph_Print"))
        self.actionCalibrate_New_Material = QtGui.QAction(MainWindow)
        self.actionCalibrate_New_Material.setObjectName(_fromUtf8("actionCalibrate_New_Material"))
        self.actionManipulate_XDFL_Files = QtGui.QAction(MainWindow)
        self.actionManipulate_XDFL_Files.setObjectName(_fromUtf8("actionManipulate_XDFL_Files"))
        self.actionVisualize_XDFL_Files = QtGui.QAction(MainWindow)
        self.actionVisualize_XDFL_Files.setObjectName(_fromUtf8("actionVisualize_XDFL_Files"))
        self.actionLaunch_Seraph_Robotics_Website = QtGui.QAction(MainWindow)
        self.actionLaunch_Seraph_Robotics_Website.setObjectName(_fromUtf8("actionLaunch_Seraph_Robotics_Website"))
        self.actionView_Software_Guide = QtGui.QAction(MainWindow)
        self.actionView_Software_Guide.setObjectName(_fromUtf8("actionView_Software_Guide"))
        self.actionView_XDFL_Calibration_Guide = QtGui.QAction(MainWindow)
        self.actionView_XDFL_Calibration_Guide.setObjectName(_fromUtf8("actionView_XDFL_Calibration_Guide"))
        self.actionHeated_Tray_Specs = QtGui.QAction(MainWindow)
        self.actionHeated_Tray_Specs.setObjectName(_fromUtf8("actionHeated_Tray_Specs"))
        self.actionTemprature_Controller_User_Guide = QtGui.QAction(MainWindow)
        self.actionTemprature_Controller_User_Guide.setObjectName(_fromUtf8("actionTemprature_Controller_User_Guide"))
        self.actionUSB_Microscope_Specs = QtGui.QAction(MainWindow)
        self.actionUSB_Microscope_Specs.setObjectName(_fromUtf8("actionUSB_Microscope_Specs"))
        self.actionUV_Tool_Specs = QtGui.QAction(MainWindow)
        self.actionUV_Tool_Specs.setObjectName(_fromUtf8("actionUV_Tool_Specs"))
        self.menuFile.addAction(self.actionExit)
        self.menuEssential_tools.addAction(self.actionLaunch_Seraph_Studio)
        self.menuEssential_tools.addAction(self.actionLaunch_Seraph_Print)
        self.menuOptional_Advanced_Tools.addAction(self.actionCalibrate_New_Material)
        self.menuOptional_Advanced_Tools.addAction(self.actionManipulate_XDFL_Files)
        self.menuOptional_Advanced_Tools.addAction(self.actionVisualize_XDFL_Files)
        self.menuHelp_Manuals_Specs.addAction(self.actionLaunch_Seraph_Robotics_Website)
        self.menuHelp_Manuals_Specs.addSeparator()
        self.menuHelp_Manuals_Specs.addAction(self.actionView_Software_Guide)
        self.menuHelp_Manuals_Specs.addAction(self.actionView_XDFL_Calibration_Guide)
        self.menuHelp_Manuals_Specs.addSeparator()
        self.menuHelp_Manuals_Specs.addAction(self.actionHeated_Tray_Specs)
        self.menuHelp_Manuals_Specs.addAction(self.actionTemprature_Controller_User_Guide)
        self.menuHelp_Manuals_Specs.addAction(self.actionUSB_Microscope_Specs)
        self.menuHelp_Manuals_Specs.addAction(self.actionUV_Tool_Specs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEssential_tools.menuAction())
        self.menubar.addAction(self.menuOptional_Advanced_Tools.menuAction())
        self.menubar.addAction(self.menuHelp_Manuals_Specs.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Seraph Scientist LabManager", None))
        self.studioButton.setText(_translate("MainWindow", "Click to launch SeraphStudio", None))
        self.calibrateButton.setText(_translate("MainWindow", "Click to launch Material Calibrator ", None))
        self.manipulateButton.setText(_translate("MainWindow", "Launch Manipulator", None))
        self.viewButton.setText(_translate("MainWindow", "Launch XDFL Viewer", None))
        self.printButton.setText(_translate("MainWindow", "Click to launch SeraphPrint", None))
        self.quitButton.setText(_translate("MainWindow", "Quite LabManager", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEssential_tools.setTitle(_translate("MainWindow", "Essential tools", None))
        self.menuOptional_Advanced_Tools.setTitle(_translate("MainWindow", "Optional & Advanced Tools", None))
        self.menuHelp_Manuals_Specs.setTitle(_translate("MainWindow", "Help Manuals & Specs", None))
        self.actionExit.setText(_translate("MainWindow", "exit", None))
        self.actionLaunch_Seraph_Studio.setText(_translate("MainWindow", "Launch Seraph Studio", None))
        self.actionLaunch_Seraph_Print.setText(_translate("MainWindow", "Launch Seraph Print", None))
        self.actionCalibrate_New_Material.setText(_translate("MainWindow", "Calibrate New Material", None))
        self.actionManipulate_XDFL_Files.setText(_translate("MainWindow", "Manipulate XDFL Files", None))
        self.actionVisualize_XDFL_Files.setText(_translate("MainWindow", "Visualize XDFL Files", None))
        self.actionLaunch_Seraph_Robotics_Website.setText(_translate("MainWindow", "Launch Seraph Robotics Website", None))
        self.actionView_Software_Guide.setText(_translate("MainWindow", "View Software Guide", None))
        self.actionView_XDFL_Calibration_Guide.setText(_translate("MainWindow", "View XDFL & Calibration Guide", None))
        self.actionHeated_Tray_Specs.setText(_translate("MainWindow", "Heated Tray Specs", None))
        self.actionTemprature_Controller_User_Guide.setText(_translate("MainWindow", "Temprature Controller User Guide", None))
        self.actionUSB_Microscope_Specs.setText(_translate("MainWindow", "USB Microscope Specs", None))
        self.actionUV_Tool_Specs.setText(_translate("MainWindow", "UV Tool Specs", None))

